### ISSUE TITLE
changing CUDA device question

### ISSUE THREAD

**Issue by persona2grata** [timeseriesAI/tsai#214]
Is there a way to change the CUDA device number using the tsai Python library? I am attempting to use train a model following the steps in the tutorial notebook and when I get to the step after "learn.save('stage0')" the next step is "learn.lr_find()" but I get the error "CUDA out of memory. Tried to allocate 12.00MiB (GPU 0; 15.90 GiB total capacity; 14.69 GiB already allocated; 6.88 MiB free; 14.70 GiB reserved in total by PyTorch)" I have (8) GPU devices on my box, but I can't seem to figure out how to tell the method to utilize a different GPU.

**Comment by oguiza** [comment]
Hi @persona2grata,

Normally you'd use: 

```
torch.cuda.set_device('cuda:0')
```

to select a specific device. The `tsai` DataLoaders picks the default_device unless one is specified. That means you could also do this: 

```
X, y, splits = get_UCR_data('LSST', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, device='cuda:0')
dls.one_batch()
```

I'm curious though, how big is your dataset? Does it fit in memory? Or is it on-disk? I've just released a new tutorial on how to work with larger-than-memory datasets. I'm not sure if it might be of any help to you.

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response. Please, reopen if necessary.

**Comment by persona2grata** [comment]
@oguiza Thank you, that solution worked for me.
